server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dragon
#    url: jdbc:postgresql://ec2-43-203-224-180.ap-northeast-2.compute.amazonaws.com:5432/dragon
    username: csw
    password: 1234
#    password: sksnzm62
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 532691097117-ted9r3n4lgl988kerkrj59ieqcnk780l.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8087/oauth2/callback/google"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 7200000 # csw-memo 240101: jwt 토큰 유효시간
  cors:
    allowedOrigins: http://dragonneolike.com,http://localhost:5173
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8087/oauth2/callback
      - http://localhost:5173/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
# todo 240313: 프로필 새로 파라
#    allowedOrigins: http://localhost:5173
cloud:
  aws:
    s3:
      bucket: emusonbucket
    credentials:
      access-key: AKIAUP625AXSLWSTTUOZ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
